name: sidekick.reviews
favicon: null
layout_spectrum: 0.8611088905017823
typography_spectrum: 0.7811389390844852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#200204'
    - '#ffa55e'
    - '#b6451d'
    - '#65a595'
  brandStrength: 1
  lightness: 0.7882302876096219
  saturation: 0.9333042060025036
  rhythmicContrast: 0.6849662971217185
purpose: []
